name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: "Test"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Check Rust code"
        run: cargo check

      - name: "Run cargo clippy"
        run: cargo clippy

      - name: "Build Rust code"
        run: cargo build

      - name: "Test Rust code"
        run: cargo test
        timeout-minutes: 10
